version: '3'

services:
  auth_db:
    build:
      dockerfile: ./dockerfiles/Dockerfile.authdb
      context: .
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345678
      - POSTGRES_DB=auth_db
    container_name: links_grouper_auth_db
    ports:
      - "5433:5432"
    networks:
      - links_grouper

  authentication:
    build:
      dockerfile: ./dockerfiles/Dockerfile.authentication
      context: .
    container_name: links_grouper_authentication
    ports:
      - "8001:8001"
    networks:
      - links_grouper
    depends_on:
      - auth_db

  app_db:
    build:
      dockerfile: ./dockerfiles/Dockerfile.appdb
      context: .
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345678
      - POSTGRES_DB=app_db
    container_name: links_grouper_db
    ports:
      - "5432:5432"
    networks:
      - links_grouper

  backend:
    build:
      dockerfile: ./dockerfiles/Dockerfile.backend
      context: .
    container_name: links_grouper_backend
    ports:
      - "8000:8000"
    networks:
      - links_grouper
    depends_on:
      - app_db
  
  frontend:
    build:
      dockerfile: ./dockerfiles/Dockerfile.front
      context: .
    container_name: links_grouper_frontend
    ports:
      - "8080:8080"
    command: /bin/sh -c "yarn && quasar dev"
    networks:
      - links_grouper
    depends_on:
      - authentication
      - backend

networks:
  links_grouper:
    driver: bridge
